Lazily download coursier

diff --git a/scalafmt b/scalafmt
--- a/scalafmt
+++ b/scalafmt
@@ -1,3 +1,16 @@
 #!/usr/bin/env bash
 
-coursier launch org.scalameta:scalafmt-cli_2.12:2.0.0-RC4 -- "$@"
+set -o pipefail
+
+declare -r scalafmt_version="2.0.0-RC4"
+
+die() { echo "Aborting: $*"; exit 1; }
+
+COURSIER=coursier
+if ! command -v $COURSIER > /dev/null 2>&1; then
+  COURSIER="$HOME/.coursier/coursier"
+  curl -Lo "$COURSIER" https://git.io/coursier-cli || die "Failed to download coursier"
+  chmod +x "$COURSIER"
+fi
+
+"$COURSIER" launch org.scalameta:scalafmt-cli_2.12:$scalafmt_version -- "$@"
