Even lazilierly download coursier

diff --git a/scalafmt b/scalafmt
--- a/scalafmt
+++ b/scalafmt
@@ -9,8 +9,10 @@ die() { echo "Aborting: $*"; exit 1; }
 COURSIER=coursier
 if ! command -v $COURSIER > /dev/null 2>&1; then
   COURSIER="$HOME/.coursier/coursier"
-  curl -Lo "$COURSIER" https://git.io/coursier-cli || die "Failed to download coursier"
-  chmod +x "$COURSIER"
+  if ! command -v $COURSIER > /dev/null 2>&1; then
+    curl -Lo "$COURSIER" https://git.io/coursier-cli || die "Failed to download coursier"
+    chmod +x "$COURSIER"
+  fi
 fi
 
 "$COURSIER" launch org.scalameta:scalafmt-cli_2.12:$scalafmt_version -- "$@"
